### ISSUE TITLE
Working perfectlu

### ISSUE THREAD

**Issue by imtangim** [abdallah-odeh/flutter_file_downloader#47]
## Describe the bug
Most probably it's causing this error with android 14. I cant figure it out. I have given every permission needed.

## To Reproduce
1. Select any android 14 device or emulator
2. Try to download any file

## Expected behavior:
`
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): Failed to handle method call
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.startDownloading(DownloadTask.java:81)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onStartDownloadingFile(MethodCallHandlerImpl.java:246)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:79)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#com.abdallah.libs/file_downloader( 6069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter ( 6069): downloadFile error: PlatformException(error, Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
I/flutter ( 6069): 	at com.odehbros.flutter_file_downloader.core.DownloadTask.startDownloading(DownloadTask.java:81)
I/flutter ( 6069): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onStartDownloadingFile(MethodCallHandlerImpl.java:246)
I/flutter ( 6069): 	at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:79)
I/flutter ( 6069): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter ( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter ( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter ( 6069): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 6069): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter ( 6069): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 6069): 	at android.os.Looper.loopOnce(Looper.java:205)
I/flutter ( 6069): 	at android.os.Looper.loop(Looper.java:294)
I/flutter ( 6069): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
I/flutter ( 6069): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 6069): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
I/flutter ( 6069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter ( 6069): )
`

## Flutter doctor
<details>
`C:\Users\RedmiBook>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.88.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.`
</details>

## Smartphone (please complete the following information):

 - OS:Android 14
 - SDK : 34
 - Plugin version: flutter_file_downloader: ^1.2.1

**Comment by abdallah-odeh** [comment]
Hello @imtangim, have you tried to perform `flutter clean` & run the app again?
also could you reproduce the issue on the example app?

my flutter version is 3.13.9 and I tested it on **Android 14 emulator with SDK 34** and it worked fine (this is not flutter related because the issue in the native code)

**Comment by abdallah-odeh** [comment]
Closing this issue for lack of activity, please if you have any other problems consider filing them or reopen this issue for a related problems
