### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by bettkipronoh** [abdallah-odeh/flutter_file_downloader#54]
## Describe the bug
Got a null point exception from firebase crashlytics
` Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void z6.k.c(java.lang.String, java.lang.Object)' on a null object reference
       at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl$2.onProgress(MethodCallHandlerImpl.java:300)
       at com.odehbros.flutter_file_downloader.downloader.DownloadManagerService.lambda$trackDownload$3(DownloadManagerService.java:178)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8061)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)`

**Comment by bettkipronoh** [comment]
Hello @abdallah-odeh , 
Am using flutter_file_downloader: ^2.0.0
Unfortunately I can't provide the url because the exception was caught from a user's device.

**Comment by abdallah-odeh** [comment]
I'll investigate in the bug and tell you what I found 
Thanks for reporting

**Comment by abdallah-odeh** [comment]
Hello @bettkipronoh, did you face this issue a lot?
actually I could not figure out the cause of the bug so I wrapped it with try & catch to avoid app to crash

**Comment by bettkipronoh** [comment]
Yes many users are affected. Here is firebase screenshot
![Screenshot from 2024-09-04 16-03-08](https://github.com/user-attachments/assets/e526f901-5ea6-42a2-ae9d-ac6fe593c9c8)

**Comment by abdallah-odeh** [comment]
Sorry to hear that, 
I will deploy a version today that avoids app crash,
I believe that the file get downloaded indeed but the callback never gets fired; so basically the code sees the task still in progress

**Comment by abdallah-odeh** [comment]
I deployed a new version `flutter_file_downloader: ^2.0.1-dev.2`, please try it out & tell me if works fine to roll it to production
